// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApp(arg1) {
  return window['go']['bridge']['App']['AddApp'](arg1);
}

export function GetConfig() {
  return window['go']['bridge']['App']['GetConfig']();
}

export function GetInstalledApps() {
  return window['go']['bridge']['App']['GetInstalledApps']();
}

export function GetTopBlockedApps() {
  return window['go']['bridge']['App']['GetTopBlockedApps']();
}

export function RemoveApp(arg1) {
  return window['go']['bridge']['App']['RemoveApp'](arg1);
}

export function SetBlockedApps(arg1) {
  return window['go']['bridge']['App']['SetBlockedApps'](arg1);
}

export function StartFocus(arg1) {
  return window['go']['bridge']['App']['StartFocus'](arg1);
}

export function StopFocus() {
  return window['go']['bridge']['App']['StopFocus']();
}
