// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApp(arg1) {
  return window['go']['bridge']['App']['AddApp'](arg1);
}

export function AddBlockedSite(arg1) {
  return window['go']['bridge']['App']['AddBlockedSite'](arg1);
}

export function AddBlockedSites(arg1) {
  return window['go']['bridge']['App']['AddBlockedSites'](arg1);
}

export function EmergencyUnlock() {
  return window['go']['bridge']['App']['EmergencyUnlock']();
}

export function GetBlockCommonVPN() {
  return window['go']['bridge']['App']['GetBlockCommonVPN']();
}

export function GetBlockedSites() {
  return window['go']['bridge']['App']['GetBlockedSites']();
}

export function GetConfig() {
  return window['go']['bridge']['App']['GetConfig']();
}

export function GetInstalledApps() {
  return window['go']['bridge']['App']['GetInstalledApps']();
}

export function GetSchedules() {
  return window['go']['bridge']['App']['GetSchedules']();
}

export function GetTopBlockedApps() {
  return window['go']['bridge']['App']['GetTopBlockedApps']();
}

export function RemoveApp(arg1) {
  return window['go']['bridge']['App']['RemoveApp'](arg1);
}

export function RemoveBlockedSite(arg1) {
  return window['go']['bridge']['App']['RemoveBlockedSite'](arg1);
}

export function RemoveBlockedSites(arg1) {
  return window['go']['bridge']['App']['RemoveBlockedSites'](arg1);
}

export function SaveSchedules(arg1) {
  return window['go']['bridge']['App']['SaveSchedules'](arg1);
}

export function SetBlockCommonVPN(arg1) {
  return window['go']['bridge']['App']['SetBlockCommonVPN'](arg1);
}

export function SetBlockedApps(arg1) {
  return window['go']['bridge']['App']['SetBlockedApps'](arg1);
}

export function StartFocus(arg1) {
  return window['go']['bridge']['App']['StartFocus'](arg1);
}

export function StopFocus() {
  return window['go']['bridge']['App']['StopFocus']();
}
