// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function AddApp(arg1:string):Promise<void>;

export function GetConfig():Promise<storage.Config>;

export function RemoveApp(arg1:string):Promise<void>;

export function StartFocus(arg1:number):Promise<void>;

export function StopFocus():Promise<void>;
