// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApp(arg1) {
  return window['go']['main']['App']['AddApp'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function RemoveApp(arg1) {
  return window['go']['main']['App']['RemoveApp'](arg1);
}

export function StartFocus(arg1) {
  return window['go']['main']['App']['StartFocus'](arg1);
}

export function StopFocus() {
  return window['go']['main']['App']['StopFocus']();
}
